name: ✨ Feature Request
description: 新しい機能の提案や改善をリクエストします。
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        機能提案ありがとうございます！以下のテンプレートに沿って詳細を記入してください。
  - type: textarea
    id: background
    attributes:
      label: 背景 (Background)
      description: この機能が必要な理由や、解決したい課題について説明してください。
      placeholder: 例：現在のシステムでは〇〇ができないため、ユーザー体験が低下している。
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: 目的 (Goal)
      description: この機能が達成する目標や、期待される効果について説明してください。
      placeholder: 例：〇〇を可能にすることで、ユーザーの生産性を向上させる。
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 完了条件 (Acceptance Criteria)
      description: この機能が「完了」と見なされるための具体的な条件を記述してください。
      placeholder: 例：
        - ユーザーが〇〇できること。
        - 〇〇のデータが正しく表示されること。
    validations:
      required: true
  - type: input
    id: branch-name
    attributes:
      label: ブランチ名 (Branch Name)
      description: この機能開発に使用する予定のブランチ名を提案してください。
      placeholder: 例：feat/add-new-feature
    validations:
      required: true
  - type: input
    id: artifacts
    attributes:
      label: 成果物 (Artifacts)
      description: この機能開発で作成される予定の主要な成果物（例：ファイルパス、APIエンドポイントなど）を記述してください。
      placeholder: 例：
        - `src/features/new_feature.py`
        - `/api/v1/new-endpoint`
    validations:
      required: false
  - type: dropdown
    id: labels
    attributes:
      label: ラベル (Labels)
      description: このIssueに適用するラベルを選択してください。複数選択可能です。
      multiple: true
      options:
        - bug
        - documentation
        - enhancement
        - feature
        - refactor
        - chore
        - hotfix
        - performance
        - security
        - ui
        - ux
        - testing
        - github
        - improvement
        - SYSTEM_ARCHITECT
    validations:
      required: false
