services:
  agent:
    build:
      context: ./${AGENT_NAME}/.build
      dockerfile: Dockerfile
    image: ${AGENT_NAME}_image
    volumes:
      - ./${AGENT_NAME}:${CONTAINER_VOLUME:-/app}
      - ./messages:${MESSAGE_DIR:-/app/messages}
      - gemini_config:${ROOT:-/root}/.gemini
    secrets:
      - gcp_access_key
      - github_token
    working_dir: ${CONTAINER_VOLUME:-/app}
    ports:
      - "${AGENT_PORT:-8080}:${AGENT_PORT:-8080}"
    environment:
      - AGENT_NAME=${AGENT_NAME:-your_agent_name}
      - MESSAGE_DIR=${MESSAGE_DIR:-/app/messages}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-your_gcp_project}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION:-us-central1}
    depends_on:
      - github_broker
      - redis
    # command: ["bash", "run.sh"]
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  github_broker:
    build:
      context: ./${BROKER_HOST}/.build
      dockerfile: Dockerfile
    image: ${BROKER_HOST}_image
    volumes:
      - ./${BROKER_HOST}:${CONTAINER_VOLUME:-/app}
      - ./messages:${MESSAGE_DIR:-/app/messages}
    secrets:
      - github_token
    working_dir: ${CONTAINER_VOLUME:-/app}
    ports:
      - "${BROKER_PORT:-8000}:${BROKER_PORT:-8000}"
    environment:
      - BROKER_PORT=${BROKER_PORT:-8000}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: ["python", "main.py"]
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  gemini_config:
    name: gemini_config
  
secrets:
  gcp_access_key:
    file: ./${GCP_ACCESS_KEY}
  github_token:
    file: ./github_token.txt