services:
  agent:
    build:
      context: ./${AGENT_NAME}/.build
      dockerfile: Dockerfile
    image: ${AGENT_NAME}_image
    volumes:
      - ./${AGENT_NAME}:${CONTAINER_VOLUME:-/app}
      - ./messages:${MESSAGE_DIR:-/app/messages}
      - gemini_config:${HOME:-/root}/.gemini
    secrets:
      - gcp_access_key
    working_dir: ${CONTAINER_VOLUME:-/app}
    ports:
      - "${AGENT_PORT:-8080}:${AGENT_PORT:-8080}"
    environment:
      - AGENT_NAME=${AGENT_NAME:-your_agent_name}
      - MESSAGE_DIR=${MESSAGE_DIR:-/app/messages}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-my_account/my_repository}
      - BROKER_HOST=${BROKER_HOST:-broker}
      - BROKER_PORT=${BROKER_PORT:-8001}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-my_github_token}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-my_gemini_api_key}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-your_gcp_project}
      - GCP_LOCATION=${GCP_LOCATION:-us-central1}
    depends_on:
      - github_broker
      - redis
    # command: ["bash", "run.sh"]
    stdin_open: true
    tty: true

  github_broker:
    build:
      context: ./${BROKER_HOST}/.build
      dockerfile: Dockerfile
    image: ${BROKER_HOST}_image
    volumes:
      - ./${BROKER_HOST}:${CONTAINER_VOLUME:-/app}
      - ./messages:${MESSAGE_DIR:-/app/messages}
    working_dir: ${CONTAINER_VOLUME:-/app}
    ports:
      - "${BROKER_PORT:-8080}:${BROKER_PORT:-8080}"
    environment:
      - BROKER_PORT=${BROKER_PORT:-8000}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-my_account/my_repository}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-my_github_token}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: ["python", "main.py"]

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  gemini_config:
  
secrets:
  gcp_access_key:
    file: ./${GCP_ACCESS_KEY}