name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  contents: write

jobs:
  build:
    runs-on: [self-hosted] # ラベルは適宜調整してください
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      # Dockerイメージにインストール済みのため、このステップは不要
      # - name: Install system dependencies
      #  run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev lsb-release

      # actions/setup-python を使うことで、pipのキャッシュが効くようになります
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 毎回依存関係をインストールする
      - name: Install dependencies
        run: pip install -e .[test,dev]
      - name: Lint with ruff
        run: ruff check .
      - name: Format with ruff
        run: ruff format --check .
      - name: Type check with mypy
        run: mypy . --ignore-missing-imports
      - name: Test with pytest
        run: pytest -m "unit" --cov=. --cov-report=xml
      - name: Server startup test
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: "test"
          GEMINI_API_KEY: "test"
          TESTING: true
          REDIS_HOST: localhost
        run: |
          echo "Starting server startup test..."
          
          # サーバーをバックグラウンドで起動し、ログをファイルに出力
          python main.py > server.log 2>&1 &
          SERVER_PID=$!
          
          echo "Server starting in background with PID: $SERVER_PID"
          
          # サーバーの起動ログを監視（最大20秒）
          timeout=20
          elapsed=0
          while ! grep -q "Application startup complete" server.log; do
            if [ $elapsed -ge $timeout ]; then
              echo "❌ Server startup timed out after $timeout seconds."
              echo "--- Server Log ---"
              cat server.log
              echo "--- End Log ---"
              # タイムアウトしたらバックグラウンドプロセスを終了させる
              kill $SERVER_PID 2>/dev/null || true
              exit 1
            fi
            sleep 1
            elapsed=$((elapsed + 1))
          done
          
          echo "✅ Server started successfully."
          echo "--- Server Log ---"
          cat server.log
          echo "--- End Log ---"

          # プロセスを終了
          echo "Stopping server..."
          kill $SERVER_PID
          wait $SERVER_PID 2>/dev/null || true
          echo "✅ Server stopped successfully"
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
