name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, x64, gpu]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -e .[test,dev]
      - name: Lint with ruff
        run: ruff check .
      - name: Test with pytest
        run: pytest
