name: Issue Branch Validator

on:
  issues:
    types: [opened, edited]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Extract Branch Name
        id: extract_branch
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          # Try to extract branch name from "ブランチ名\n`branch-name`" format
          BRANCH_NAME=$(echo "$ISSUE_BODY" | grep -oP '(?<=^ブランチ名\n`)[^`]+(?=`$)' || echo "$ISSUE_BODY" | grep -oP '(?<=^ブランチ名: )[^
]+')
          echo "Extracted Branch Name: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Check for Duplicate Branch Name
        id: check_duplicate
        if: steps.extract_branch.outputs.branch_name != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.extract_branch.outputs.branch_name }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          CURRENT_ISSUE_NUMBER="${{ github.event.issue.number }}"

          # Search for open issues with the same branch name in their body
          # Exclude the current issue from the search
          DUPLICATE_ISSUES=$(gh api \
            --method GET \
            -H "Accept: application/vnd.github.v3+json" \
            "/repos/$OWNER/$REPO/issues" \
            -F state=open \
            -F per_page=100 \
            --jq ".[] | select(.number != $CURRENT_ISSUE_NUMBER and (.body | contains(\"ブランチ名: $BRANCH_NAME\") or .body | contains(\"ブランチ名\n`$BRANCH_NAME`\"))) | .number")

          if [ -n "$DUPLICATE_ISSUES" ]; then
            echo "Duplicate branch name found in issue(s): $DUPLICATE_ISSUES"
            echo "is_duplicate=true" >> "$GITHUB_OUTPUT"
          else
            echo "No duplicate branch name found."
            echo "is_duplicate=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Add Comment and Label if Duplicate
        if: steps.check_duplicate.outputs.is_duplicate == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_AUTHOR="${{ github.event.issue.user.login }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"

          COMMENT_BODY="@$ISSUE_AUTHOR このブランチ名は他のIssueで既に使用されています。変更してください。"
          
          # Add comment
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            "/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/comments" \
            -F body="$COMMENT_BODY"

          # Add label
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            "/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/labels" \
            -F labels[]="branch-conflict"
        shell: bash
